### ISSUE TITLE
Legacy and no-legacy builds fail

### ISSUE THREAD

**Issue by LeoMartinDev** [utoppo/vue-cli-plugin-electron-builder-build-problem#1] opened 2019-02-08 16:15 UTC
Hello,
I just tried your fix but still have issues when building my app :

```
Template execution failed: TypeError: Cannot read property 'app' of undefined

  TypeError: Cannot read property 'app' of undefined

  - loader_window.html:17203
   ***/loader_window.html:17203:70

  - loader_window.html:17206 5e0b.module.exports
    ****/loader_window.html:17206:3

  - index.js:284 Promise.resolve.then
    [toolbox-vue-cli]/[html-webpack-plugin]/index.js:284:18


(node:14432) UnhandledPromiseRejectionWarning: Build failed with errors.
(node:14432) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:14432) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 79.69s.
```

Any idea ?

**Comment by LeoMartinDev** [comment] 2019-02-08 16:37
It looks like I'm not able to use ejs / node in my second_window.html

**Comment by utoppo** [comment] 2019-02-08 19:43
As you mentioned in [https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/182#issuecomment-461855657](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/182#issuecomment-461855657) the build even fails with the `--legacy` flag.

I think you might have a different problem, but really hard to say without knowing your code. Could you provide more context, or a repository to reproduce your problem?

**Comment by LeoMartinDev** [comment] 2019-02-08 20:05
I was using ejs & node in my html which seems unsupported in the second window.
I will provide some reproduction code tomorrow

**Comment by utoppo** [comment] 2019-02-08 22:23
Using `node` and `ejs` works for me in both windows, see branch [ejs](https://github.com/utoppo/vue-cli-plugin-electron-builder-build-problem/tree/ejs). The `templateParameters` for each html-file are assigned in `vue.config.js`.  

Looks like inside `ejs`-tags, you can only use `templateParameters` that exist at build-time, no variables that are dynamically generated at runtime. Could this be the problem?

**Comment by utoppo** [comment] 2019-02-13 15:06
Did you already make some progress on the issue?

**Comment by utoppo** [comment] 2019-03-06 11:18
Should be fixed in [https://github.com/nklayman/vue-cli-plugin-electron-builder](https://github.com/nklayman/vue-cli-plugin-electron-builder) itself. My workaround is not needed anymore and also does not work in the newest version of the plugin. See: [https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/182#issuecomment-469838147](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/182#issuecomment-469838147). Therefore closing this issue.

**Closed as completed by utoppo** 2019-03-06 11:18 UTC
